### ISSUE TITLE
no loadMessages in resolved Modules found

### ISSUE THREAD

**Issue by Plorenzo** [opral/inlang-paraglide-js#184]
Creating issue as requested by cli. 

```
WARN  Failed to create a new inlang project.

This is likely an internal bug. Please file an issue at https://github.com/opral/monorepo
```

I just ran this `npx @inlang/paraglide-sveltekit init` to add paraglide to my project. 

Looks like some fetch failed, but If i tried those url in my browser or with curl, I get a response without issues. 

```
npx @inlang/paraglide-sveltekit init           130 ↵
Need to install the following packages:
@inlang/paraglide-sveltekit@0.11.0
Ok to proceed? (y) y

Using existing cloned repo

✔ Which languages do you want to support?
en, es, gl
ℹ Creating a new inlang project in the current working directory.

 WARN  Failed to create a new inlang project.

This is likely an internal bug. Please file an issue at https://github.com/opral/monorepo.


 ERROR  no loadMessages in resolved Modules found

  at Object.fn (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:9246:34)
  at runComputation (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7268:23)
  at updateComputation (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7261:3)
  at runTop (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7330:7)
  at runUserEffects (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7387:5)
  at /Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7371:22
  at runUpdates (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7351:17)
  at completeUpdates (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7371:5)
  at runUpdates (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7352:5)
  at writeSignal (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7225:7)


 ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js":

ModuleImportError: Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js":

TypeError: fetch failed


  ModuleImportError: Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-empty-pattern@latest/dist/index.js":

  TypeError: fetch failed
  at resolveModule (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:6980:25)
  at processTicksAndRejections (node:internal/process/task_queues:95:5)
  at runNextTicks (node:internal/process/task_queues:64:3)
  at process.processImmediate (node:internal/timers:454:9)
  at async Promise.all (index 0)
  at async resolveModules (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7021:3)


 ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js":

ModuleImportError: Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js":

TypeError: fetch failed


  ModuleImportError: Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js":

  TypeError: fetch failed
  at resolveModule (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:6980:25)
  at processTicksAndRejections (node:internal/process/task_queues:95:5)
  at runNextTicks (node:internal/process/task_queues:64:3)
  at process.processImmediate (node:internal/timers:454:9)
  at async Promise.all (index 1)
  at async resolveModules (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7021:3)


 ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js":

ModuleImportError: Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js":

TypeError: fetch failed


  ModuleImportError: Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js":

  TypeError: fetch failed
  at resolveModule (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:6980:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Promise.all (index 2)
  at async resolveModules (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7021:3)


 ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js":

ModuleImportError: Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js":

TypeError: fetch failed


  ModuleImportError: Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js":

  TypeError: fetch failed
  at resolveModule (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:6980:25)
  at processTicksAndRejections (node:internal/process/task_queues:95:5)
  at runNextTicks (node:internal/process/task_queues:64:3)
  at process.processImmediate (node:internal/timers:454:9)
  at async Promise.all (index 3)
  at async resolveModules (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7021:3)


 ERROR  Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js":

ModuleImportError: Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js":

TypeError: fetch failed


  ModuleImportError: Couldn't import the plugin "https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js":

  TypeError: fetch failed
  at resolveModule (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:6980:25)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Promise.all (index 4)
  at async resolveModules (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7021:3)


 ERROR  No plugin provides a loadMessages() or saveMessages() function

In case no plugin threw an error, you likely forgot to add a plugin that handles the loading and saving of messages. Refer to the marketplace for available plugins https://inlang.com/marketplace.


  In case no plugin threw an error, you likely forgot to add a plugin that handles the loading and saving of messages. Refer to the marketplace for available plugins https://inlang.com/marketplace.
  at resolvePlugins (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:6955:24)
  at resolveModules (/Users/plorenzo/.npm/_npx/d166e665619d8c59/node_modules/@inlang/paraglide-js/dist/index.js:7022:33)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by LorisSigrist** [comment]
This error looks like it's caused by an issue fetching from JsDelivr. It's possible that JSDelivr loads fine in the browser but fails programmatically because of differences in caching. 

Does this still happen?

**Comment by samuelstroschein** [comment]
Closing because stale
