### ISSUE TITLE
Sveltekit: Build error with Sentry

### ISSUE THREAD

**Issue by testvinder** [opral/inlang-paraglide-js#192]
When having both Paraglide and Sveltekit installed I'm getting this build error. Have anyone experienced anything similar or know why it might happening? It happens both when building locally and in production.

```
error during build:
[vite:load-fallback] Could not load /vercel/path0/src/paraglide/sentry-release-injection-file (imported by src/paraglide/messages.js): The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/vercel/path0/src/paraglide/\x00sentry-release-injection-file'
TypeError [PLUGIN_ERROR]: Could not load /vercel/path0/src/paraglide/sentry-release-injection-file (imported by scr/paraglide/messages.js): The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/vercel/path0/src/paraglide/\x00sentry-release-injection-file'
    at open (node:internal/fs/promises:636:10)
    at Object.readFile (node:internal/fs/promises:1249:20)
    at Object.load (file:///vercel/path0/node_modules/vite/dist/node/chunks/dep-Cy9twKMn.js:64973:35)
    at async PluginDriver.hookFirstAndGetPlugin (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:19494:28)
    at async file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:18665:33
    at async Queue.work (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:19704:32)
Error: Command "npm run build" exited with 1
```

**Comment by SaintPepsi** [comment]
I was having this as well, had to not include the sentry plugin for the time being

**Comment by chadsr** [comment]
Seeing this as well.

**Comment by chbert** [comment]
same here

**Comment by martinhjartmyr** [comment]
Seeing this error as well when trying to add Sentry to my project. Any updates? 

`vite dev` - works fine
`vite build` - fails with error above

**Comment by testvinder** [comment]
Has anyone found a workaround for this?

**Comment by chbert** [comment]
Did anyone try to add an explicit releas version in Sentry.Init?

`release: '{{ yourAppName }}@1.0.0'`

**Comment by dror-weiss** [comment]
I have the exact same issue. I want both Sentry and translations being deployed in my CI but it has the following error:
```bash
x Build failed in 1.90s
error during build:
[vite:load-fallback] Could not load /home/runner/work/town-center/town-center/company/apps/app.company.com/sveltekit-website/src/lib/paraglide/sentry-release-injection-file (imported by src/lib/paraglide/messages.js): The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/home/runner/work/repo/company/apps/app.company.com/sveltekit-website/src/lib/paraglide/\x00sentry-relea...
```

Local works fine; the above is produced in Github Actions.

**Comment by TazorDE** [comment]
We're seeing the same issue. I'll try to follow up tomorrow after I evaluate workarounds
```
error during build:
[vite:load-fallback] Could not load /vercel/path0/src/paraglide/sentry-release-injection-file (imported by src/paraglide/runtime.js): The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/vercel/path0/src/paraglide/\x00sentry-release-injection-file'
TypeError [PLUGIN_ERROR]: Could not load /vercel/path0/src/paraglide/sentry-release-injection-file (imported by src/paraglide/runtime.js): The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/vercel/path0/src/paraglide/\x00sentry-release-injection-file'
    at open (node:internal/fs/promises:636:10)
    at Object.readFile (node:internal/fs/promises:1242:20)
    at Object.load (file:///vercel/path0/node_modules/.pnpm/vite@5.4.3_@types+node@20.11.30/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:65013:35)
    at async PluginDriver.hookFirstAndGetPlugin (file:///vercel/path0/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:19818:28)
    at async file:///vercel/path0/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:18999:33
    at async Queue.work (file:///vercel/path0/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:20028:32)
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1
```

**Comment by TazorDE** [comment]
Ok, I found the root cause of the issue. The paraglide vite plugin resolves all files during the build process. If any filename contains a NULL character (like some vite virtual modules do) the paraglide-process that happens during `vite build` doesn't check if the paths contain NULL characters. 

> If your plugin uses 'virtual modules' (e.g. for helper functions), prefix the module ID with \0. This prevents other plugins from trying to process it. (https://rollupjs.org/plugin-development/#conventions)

Paraglide doesn't use `virtual modules`, but if other plugins use them paraglide inevitably will touch them. 
In order to fix this a simple check can be introduced [here](https://github.com/opral/monorepo/blob/6cb759283e8b2ab6ac26a24928adccb06285dac8/inlang/source-code/paraglide/paraglide-unplugin/src/index.ts#L163) like so:
```ts
//...
    vite: {
		apply: "build",
		resolveId(id, importer) {
		    // NEW
		    // if the id contains a null char ignore it since it should be a vite virtual module
                    // this helps support other vite plugins (like sentry) that make heavy use of these types of file-namings
                    if (id.includes("\0"))
                        return undefined;
		    // END NEW
			// resolve relative imports inside the output directory
			// the importer is alwazs normalized
			if (importer?.startsWith(normalizedOutdir)) {
//...
```

**Comment by samuelstroschein** [comment]
@TazorDE thanks for finding the bug. I unassigned Loris. Ready to accept a PR 😎 more info on discord https://discord.com/channels/897438559458430986/1083724234142011392/1308433130855600148
