### ISSUE TITLE
New Svelte 5 syntax `<script module>` breaks Paraglide integration

### ISSUE THREAD

**Issue by wojexe** [opral/inlang-paraglide-js#196]
### General

As stated in the title, the recent update to Svelte 5 has caused Paraglide integration to break. More precisely, updating code to fix the warnings the recent version of Svelte 5 produces - changing `<script context="module" ...>` into `<script module ...>` causes the Paraglide compiler to error out.

See related:
- [Svelte 5.0.0-next.232 GH release page](https://github.com/sveltejs/svelte/releases/tag/svelte%405.0.0-next.232)
- [Updates for extensions](https://github.com/sveltejs/language-tools/releases/tag/extensions-108.6.1)

### Logs

```
transforming (433) node_modules/@sveltejs/kit/node_modules/devalue/src/parse.js[@inlang/paraglide-sveltekit] Failed to parse <repo_root>/src/lib/components/ui/tree/dialogs/edit-person-dialog.svelte. Link translations were NOT applied. CompileError: A component can have a single top-level `<script>` element and/or a single top-level `<script context="module">` element
    at e (file://<repo_root>/node_modules/@inlang/paraglide-sveltekit/node_modules/svelte/src/compiler/errors.js:56:8)
    at Module.script_duplicate (file://<repo_root>/node_modules/@inlang/paraglide-sveltekit/node_modules/svelte/src/compiler/errors.js:975:2)
    at tag (file://<repo_root>/node_modules/@inlang/paraglide-sveltekit/node_modules/svelte/src/compiler/phases/1-parse/state/element.js:308:29)
    at new Parser (file://<repo_root>/node_modules/@inlang/paraglide-sveltekit/node_modules/svelte/src/compiler/phases/1-parse/index.js:87:12)
    at parse (file://<repo_root>/node_modules/@inlang/paraglide-sveltekit/node_modules/svelte/src/compiler/phases/1-parse/index.js:311:17)
    at parse (file://<repo_root>/node_modules/@inlang/paraglide-sveltekit/node_modules/svelte/src/compiler/index.js:148:9)
    at markup (file://<repo_root>/node_modules/@inlang/paraglide-sveltekit/dist/vite/preprocessor/index.js:46:24)
    at process_markup (file://<repo_root>/node_modules/svelte/src/compiler/preprocess/index.js:309:26)
    at Module.preprocess (file://<repo_root>/node_modules/svelte/src/compiler/preprocess/index.js:356:31)
    at async compileSvelte (file://<repo_root>/node_modules/@sveltejs/vite-plugin-svelte/src/utils/compile.js:85:20) {
  filename: undefined,
  position: [ 817, 817 ],
  start: { line: 34, column: 0, character: 817 },
  end: { line: 34, column: 0, character: 817 },
  code: 'script_duplicate'
}
```

**Comment by samuelstroschein** [comment]
Re-open if still relevant. The SvelteKit adapter has been updates to Svelte 5.
