### ISSUE TITLE
[Paraglide Next] Next Tubro mode throws MODULE_UNPARSEABLE

### ISSUE THREAD

**Issue by r0skar** [opral/inlang-paraglide-js#198]
Hei,

I noticed something weird. When running my project with `next dev --turbo`, imports from the i18n navigation utilities throw an error. This does **not** happen when I run without `turbo`.

```
⨯ Error: Could not parse module '[project]/node_modules/next/dist/server/future/route-modules/app-route/vendored/contexts/router-context.js'
at Object.<anonymous> (/vault/dev/work/project/.next/server/chunks/node_modules_f61e72._.js:13410:11)
at [project]/node_modules/next/dist/server/future/route-modules/app-route/vendored/contexts/router-context.js [app-route] (ecmascript) (/vault/dev/work/project/.next/server/chunks/node_modules_f61e72._.js:13413:3)
at instantiateModule (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:520:23)
at getOrInstantiateModuleFromParent (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:572:12)
at commonJsRequire (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:136:20)
at Object.<anonymous> (/vault/dev/work/project/.next/server/chunks/node_modules_f61e72._.js:13755:37)
at [project]/node_modules/next/dist/client/link.js [app-route] (ecmascript) (/vault/dev/work/project/.next/server/chunks/node_modules_f61e72._.js:14173:3)
at instantiateModule (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:520:23)
at getOrInstantiateModuleFromParent (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:572:12)
at commonJsRequire (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:136:20)
at Object.<anonymous> (/vault/dev/work/project/.next/server/chunks/node_modules_f61e72._.js:14176:18)
at [project]/node_modules/next/link.js [app-route] (ecmascript) (/vault/dev/work/project/.next/server/chunks/node_modules_f61e72._.js:14178:3)
at instantiateModule (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:520:23)
at getOrInstantiateModuleFromParent (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:572:12)
at esmImport (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:122:20)
at /vault/dev/work/project/.next/server/chunks/node_modules_f61e72._.js:14221:134
at [project]/node_modules/@inlang/paraglide-next/dist/paraglide-next/src/app/navigation/Link.js [app-route] (ecmascript) (/vault/dev/work/project/.next/server/chunks/node_modules_f61e72._.js:14284:3)
at instantiateModule (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:520:23)
at getOrInstantiateModuleFromParent (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:572:12)
at esmImport (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:122:20)
at /vault/dev/work/project/.next/server/chunks/node_modules_f61e72._.js:14293:216
at [project]/node_modules/@inlang/paraglide-next/dist/paraglide-next/src/app/navigation/navigation.server.js [app-route] (ecmascript) (/vault/dev/work/project/.next/server/chunks/node_modules_f61e72._.js:14315:3)
at instantiateModule (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:520:23)
at getOrInstantiateModuleFromParent (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:572:12)
at esmImport (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:122:20)
at /vault/dev/work/project/.next/server/chunks/node_modules_f61e72._.js:14689:232
at [project]/node_modules/@inlang/paraglide-next/dist/app/index.server.js [app-route] (ecmascript) <module evaluation> (/vault/dev/work/project/.next/server/chunks/node_modules_f61e72._.js:14699:3)
at instantiateModule (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:520:23)
at getOrInstantiateModuleFromParent (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:572:12)
at esmImport (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:122:20)
at /vault/dev/work/project/.next/server/chunks/_0286e4._.js:73:213
at [project]/lib/i18n/index.ts [app-route] (ecmascript) (/vault/dev/work/project/.next/server/chunks/_0286e4._.js:92:3)
at instantiateModule (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:520:23)
at getOrInstantiateModuleFromParent (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:572:12)
at esmImport (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:122:20)
at /vault/dev/work/project/.next/server/chunks/_0286e4._.js:166:126
at [project]/lib/auth/index.ts [app-route] (ecmascript) (/vault/dev/work/project/.next/server/chunks/_0286e4._.js:255:3)
at instantiateModule (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:520:23)
at getOrInstantiateModuleFromParent (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:572:12)
at esmImport (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:122:20)
at /vault/dev/work/project/.next/server/chunks/_0286e4._.js:351:126
at [project]/lib/project/service.ts [app-route] (ecmascript) (/vault/dev/work/project/.next/server/chunks/_0286e4._.js:522:3)
at instantiateModule (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:520:23)
at getOrInstantiateModuleFromParent (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:572:12)
at esmImport (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:122:20)
at /vault/dev/work/project/.next/server/chunks/_0286e4._.js:534:130
at [project]/app/(web)/api/refresh-token/route.ts [app-route] (ecmascript) (/vault/dev/work/project/.next/server/chunks/_0286e4._.js:547:3)
at instantiateModule (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:520:23)
at getOrInstantiateModuleFromParent (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:572:12)
at esmImport (/vault/dev/work/project/.next/server/chunks/[turbopack]_runtime.js:122:20) {
code: 'MODULE_UNPARSEABLE',
page: '/api/refresh-token'
}
```

Its happening when I use `redirect` in a route handler.

```tsx
// lib/i18n.ts
export const { Link, useRouter, usePathname, redirect, permanentRedirect } = Navigation({
  strategy,
});

// route.tsx
import { redirect } from "~/lib/i18n";

export async function GET() {
  redirect("/");
}
```

**Comment by dohooo** [comment]
Have u solved this problem?
