### ISSUE TITLE
Images with Sveltekit

### ISSUE THREAD

**Issue by EcksDy** [opral/inlang-paraglide-js#233]
Hello,

I've been trying out paraglide for a static site with sveltekit(`@sveltejs/adapter-static`), and I can't seem to get the images import to work.

In sveltekit the [suggested way of importing images](https://kit.svelte.dev/docs/images#vite-s-built-in-handling) is to import through the script tag first, then use in an image tag as such:
```ts
import image from '$lib/assets/image.png';
...

<img src={image} />
```

When using paraglide and building the actual static output, vite fails because assets url gets prefixed with a language:
```
 302 /assets/image.png -> /en/assets/image.png
SvelteKitError: Not found: /en/assets/image.png
...

Error: 404 /en/assets/image.png (linked from /assets/images/image.png)
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///.../node_modules/@sveltejs/kit/src/core/config/options.js:202:13
    at file:///.../node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:65:25
    at save (file:///.../node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:413:4)
    at visit (file:///.../node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)
```

What would you suggest to do in this case? 
I've tried to find something on the matter in the docs, but couldnt find anything.

**Comment by EcksDy** [comment]
A workaround is to use handleHttpError as suggested in the error message. 
While it works, it still throws 404's in the build logs:

`svelte.config.js`
```js
import { availableLanguageTags } from './src/lib/paraglide/runtime.js';
// ...

const config = {
  kit: {
    prerender: {
      handleHttpError: ({ path, message }) => {
        const prefixedAssetsMatcher = new RegExp(
          `\\/(?:${availableLanguageTags.join('|')})\\/assets`,
        );
        const isAssetsDir = path.match(prefixedAssetsMatcher);
        if (isAssetsDir) {
          // ignore 404 errors for assets
          return;
        }

        // otherwise fail the build
        throw new Error(message);
      },
    },
  },
};

export default config;
```

**Comment by samuelstroschein** [comment]
Add `/assets` to the exclusion list of i18n routing [https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n/advanced-usage](https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n/advanced-usage). 

I'll add this problem to [https://github.com/opral/inlang-paraglide-js/issues/217](https://github.com/opral/inlang-paraglide-js/issues/217). It seems like an opt-in "these routes should be translated" instead of an opt-out "don't translate these routes" makes routing more transparent and avoids bugs like these. Do you agree?

**Comment by EcksDy** [comment]
@samuelstroschein 
I've actually tried this, I'll elaborate the process in case someone else is struggling with this. In all of the following attempts I've disabled the workaround mentioned above.

In the actual code the image actually sits in an `images` subfolder, and `/assets` initially didn't match it. Once I figured it out I've tried using a regex.  

`exclude: [/\/assets.*/]` or `exclude: [/.*\/assets.*/]` will yield this error:
```
// doesnt have this line, which means paraglide is no longer translating assets:
// 302 /assets/images/image.png -> /en/assets/images/image.png

SvelteKitError: Not found: /assets/images/image.png

Error: 404 /assets/image.png (linked from /en/about)
```
_might be a good idea to add `/assets` regex to the docs, as the current example felt like it was meant for pages only_

`linked from /en/about` was weird to me, since it's a page where I'm not using this image.
This image is referenced indirectly as a prop for SEO component inside my `layout.svelte`:

```
import SvelteSeo from 'svelte-seo';

const openGraph = {
    type: 'website',
    url: `https://some-site.com/${languageTag()}`,
    title,
    description,
	images: [
	  {
	    url: `https://some-site.com/assets/image.png`,
	    width: 300,
	    height: 300,
	    alt: 'Some image',
	  },
	],
  };

// ...

<SvelteSeo {openGraph} />
```

In `svelte.config.js` I've have the prerender origin set as such:
```js
const config = {
  kit: {
    prerender: {
      origin: 'https://some-site.com',
    },
  },
};
```

At this point I'm not sure if this is a paraglide issue or sveltekits prerender, seems like the latter.

Thing is, even with the workaround active, if I have the correct exclude present, the build will keep failing. So I've commented out the exclude, and the build works. The SEO tag is also present in its correct form, so there's something finicky there.

---

Regarding the opt-in/out, I actually like the way it is right now. Aside from the docs that could be a little clearer on what the exclude is for, in my current project it makes sense to make it opt-out, as the majority of my routes need translation. Something about the wording made me think it's a

I was surprised by the images issue though, maybe exclude any routes that have an explicit image/binary extension by default?

**Comment by samuelstroschein** [comment]
Thanks for the elaborate reply. I understand that a root cause problem is not opt-out but the naive localization of every route (instead of just pages). 

> Regarding the opt-in/out, I actually like the way it is right now. 

Noted. 

> I was surprised by the images issue though, maybe exclude any routes that have an explicit image/binary extension by default?

I agree. Translating routes for assets seems to make little sense. I assume it's a bug.

**Comment by samuelstroschein** [comment]
Closing this as "solved in the paraglide js 2.0 beta" which does not use AST transforms anymore that auto inject locale stuff into paths to avoid issues like this one
