### ISSUE TITLE
`getLanguage` breaks with Next.js 15 due to async request API breaking change

### ISSUE THREAD

**Issue by asterikx** [opral/inlang-paraglide-js#245]
Starting with latest RC of Next.js 15 (RC 2), the request APIs including `headers()` is async: https://nextjs.org/blog/next-15-rc2#async-request-apis-breaking-change

This change breaks the `getLanguage()` function from `@inlang/paraglide-next` (on the server):

https://github.com/opral/monorepo/blob/a0aaf620811b580e478a3d4add22e4c5475cbcc3/inlang/source-code/paraglide/paraglide-next/src/app/getLanguage.server.ts#L14

The `getLanguage()` function (and therefore every function that uses it) would have to be changed to an async function.

**Comment by samuelstroschein** [comment]
I feared that the Next 15 changes will impact the next adapter. Will have to wait for the metaframework overhaul project

**Comment by mrthinger** [comment]
> I feared that the Next 15 changes will impact the next adapter. Will have to wait for the metaframework overhaul project

any idea on the eta for that?

**Comment by samuelstroschein** [comment]
Estimate is Q1 2025 for https://github.com/opral/inlang-paraglide-js/issues/217. 

But I can invest time into reviewing, merging, and publishing a PR. Thus, if anyone wants to fix NextJS 15 support, please open a PR :)

**Comment by asterikx** [comment]
I did patch the package locally (seems to work fine). I can create a PR tomorrow.

**Comment by iStorry** [comment]
> I did patch the package locally (seems to work fine). I can create a PR tomorrow.

I tried making some changes, but I'm encountering other errors for some reason.

```ts
async function getLanguage() {
    try {
        const allHeader = await headers();
        const langHeader = allHeader.get(PARAGLIDE_LANGUAGE_HEADER_NAME);
        ....
```

**Comment by harrisrobin** [comment]
would appreciate if you could share your fix on this @asterikx . I'm experiencing issues as well.

**Comment by tconroy** [comment]
+1 to above, running into this. would be great to push up as a branch we can install from in the meantime.

**Comment by tconroy** [comment]
I've opened a PR here: https://github.com/opral/monorepo/pull/3188 

Unfortunately I wasn't able to run/test it locally, but perhaps it's a useful jumping off point to resolve this issue.

**Comment by asterikx** [comment]
Here's my patch file created using `bun patch @inlang/paraglide-next`: [@inlang%2Fparaglide-next@0.6.0.patch](https://github.com/user-attachments/files/17531891/%40inlang.2Fparaglide-next%400.6.0.patch)

Seems to work just fine for me at the moment.

**Comment by gerardmarquinarubio** [comment]
Bumping for visibility


> Here's my patch file created using `bun patch @inlang/paraglide-next`: [@inlang%2Fparaglide-next@0.6.0.patch](https://github.com/user-attachments/files/17531891/%40inlang.2Fparaglide-next%400.6.0.patch)
> 
> Seems to work just fine for me at the moment.

Do you know how to use the patchfile from bun directly? Couldn't find any documentation.

**Comment by tconroy** [comment]
@gerardmarquinarubio add a `patchedDependencies` key to your `package.json`, with the value being an object that maps `"dependency@version": "patches/patchName.patch" file.

Something like this (typing on phone so apologies for typos):

```json
{
  "patchedDependencies": {
    "@inlang/paraglide-next@0.6.0": "patches/@inlang/paraglide-next@0.6.0.patch"
  }
}
```

**Comment by samuelstroschein** [comment]
https://github.com/opral/monorepo/pull/3188 has been merged and published as v0.7. Thanks @tconroy for the PR!


![CleanShot 2024-10-29 at 17 27 01@2x](https://github.com/user-attachments/assets/2b504fc7-4381-4f3f-a555-51fdc81e05e5)

**Comment by gerardmarquinarubio** [comment]
I'm getting `Error: `headers` was called outside a request scope.` Just as I updated to paraglide-next@latest.

Will try to give a repo to reproduce in a few minutes.

**Comment by gerardmarquinarubio** [comment]
@samuelstroschein @tconroy 

Clone the repo, `bun dev`, you will get the error.

https://github.com/gerardmarquinarubio/paraglide-next-headers-bug

The minimal repo was as easy to reproduce as just creating a next-app using the CLI and initializing paraglide-next through the CLI.

**Comment by samuelstroschein** [comment]
@gerardmarquinarubio thanks for the repro. Highly appreciated if you can open a follow up pr to fix the issue

**Comment by asterikx** [comment]
I'm getting more errors:
```
  12 | async function getLanguage() {
  13 |     try {
> 14 |         const langHeader = await headers().get(PARAGLIDE_LANGUAGE_HEADER_NAME);
     |                                       ^
  15 |         const lang = isAvailableLanguageTag(langHeader) ? langHeader : sourceLanguageTag;
  16 |         return lang;
  17 |     }
 ⨯ unhandledRejection: Error: `headers` was called outside a request scope. Read more: https://nextjs.org/docs/messages/next-dynamic-api-wrong-context
 ```

Instead of:
```ts
 const langHeader = (await headers()).get(PARAGLIDE_LANGUAGE_HEADER_NAME);
 ```
it needs to be:
 ```ts
 const langHeader = (await headers()).get(PARAGLIDE_LANGUAGE_HEADER_NAME);
 ```

**Comment by samuelstroschein** [comment]
Yeah that makes sense. I'll fix it.

**Comment by samuelstroschein** [comment]
Released as 0.7.1

**Comment by iStorry** [comment]
> Released as 0.7.1

```ts
Error: `headers` was called outside a request scope. Read more: https://nextjs.org/docs/messages/next-dynamic-api-wrong-context
    at getExpectedRequestStore (webpack-internal:///(shared)/./node_modules/next/dist/esm/server/app-render/work-unit-async-storage.external.js:26:11)
    at headers (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/request/headers.js:76:127)
    at getLanguage (webpack-internal:///(middleware)/./node_modules/@inlang/paraglide-next/dist/paraglide-next/src/app/getLanguage.server.js:21:88)
    at eval (webpack-internal:///(middleware)/./node_modules/@inlang/paraglide-next/dist/paraglide-next/src/app/providers/LanguageProvider.js:15:148)
    at eval (webpack-internal:///(middleware)/./node_modules/@inlang/paraglide-next/dist/paraglide-next/src/app/providers/LanguageProvider.js:16:3)
    at (middleware)/./node_modules/@inlang/paraglide-next/dist/paraglide-next/src/app/providers/LanguageProvider.js (/my-app/.next/server/src/middleware.js:258:1)
    at __webpack_require__ (my-app/.next/server/edge-runtime-webpack.js:37:33)
    at fn (my-app/.next/server/edge-runtime-webpack.js:281:21)
    at eval (webpack-internal:///(middleware)/./node_modules/@inlang/paraglide-next/dist/app/index.server.js:13:111)
    ```
  
The feature works well, but I keep getting the same problem when I build or use the cold star mode.

**Comment by asterikx** [comment]
Yes, I unfortunately keep getting the same error as well:
```
  12 | async function getLanguage() {
  13 |     try {
> 14 |         const langHeader = (await headers()).get(PARAGLIDE_LANGUAGE_HEADER_NAME);
     |                                        ^
  15 |         const lang = isAvailableLanguageTag(langHeader) ? langHeader : sourceLanguageTag;
  16 |         return lang;
  17 |     }
 ⨯ unhandledRejection: Error: `headers` was called outside a request scope. Read more: https://nextjs.org/docs/messages/next-dynamic-api-wrong-context
```

**Comment by samuelstroschein** [comment]
@asterikx did that happen with your patch file too? 

if not, can you open a PR with the diff of your patch file?

**Comment by asterikx** [comment]
@samuelstroschein I did some more trial and error, and I could get rid of the error by:

1. Removing/commenting out the top-level call to `getLanguage` in the `LanguageProvider` (I'm not sure about its implications):
```diff
diff --git a/dist/paraglide-next/src/app/providers/LanguageProvider.js b/dist/paraglide-next/src/app/providers/LanguageProvider.js
index 16cd65d717b250ec9644b5057b810f48cad0157d..dda9b90cbceb94ce909ca0f640a9d9315fd0f21c 100644
--- a/dist/paraglide-next/src/app/providers/LanguageProvider.js
+++ b/dist/paraglide-next/src/app/providers/LanguageProvider.js
@@ -3,9 +3,9 @@ import { setLanguageTag, languageTag } from '$paraglide/runtime.js';
 import { ClientLanguageProvider } from './ClientLanguageProvider.js';
 import { getLanguage } from '../getLanguage.server.js';
 
-(async () => {
-    setLanguageTag(await getLanguage());
-})();
+// (async () => {
+//     setLanguageTag(await getLanguage());
+// })();
 //If we can reliably call setLanguageTag() from middleware.tsx, we can probably get rid of this component
 async function LanguageProvider(props) {
     setLanguageTag(await getLanguage());
```

2. Removing any calls to `initializeLanguage` in server actions as described in the docs here: https://inlang.com/m/osslbuzt/paraglide-next-i18n/advanced/usage-on-the-server.
However, this forces me to pass the user's locale in any call to `m` functions, i.e. `m.welcomeMessage(undefined, { languageTag: 'de-DE' })`.

I'm curious, if there is a better way to handle server actions. Possibly need to call `initializeLanguage` in server action bodies instead of calling it top-level.

**Comment by tylkomat** [comment]
I was just about the add a comment the moment you sent your comment @asterikx 
I was just doing your nr. 1 and that looks to be enough.

**Comment by samuelstroschein** [comment]
Okay, I was already surprised why the anonymous function was called in language provider. I will publish another patch hoping that it works. 

It's unfortunate that i can't invest into an e2e nextjs 15 test atm to catch bugs before publishing a patch

**Comment by samuelstroschein** [comment]
Published as `0.7.2`

**Comment by samuelstroschein** [comment]
The fix has been reverted because async headers do not have the same behavior as sync headers; see https://github.com/opral/inlang-paraglide-js/issues/255#issuecomment-2555939751. 

- the warning does not effect logic
- the warning disappears in production 
- waiting for next js to fix their async headers or someone makes a PR with a different approach than headers, see https://github.com/opral/inlang-paraglide-js/issues/255#issuecomment-2555939751

**Comment by samuelstroschein** [comment]
I invested another two hours (!). The warning has no impact on the usability. But, NextJS has to fix their APIs to resolve this issue. 

By making the `cookie(), header()` etc APIs async in Next JS 15, [despite them being sync under the hood](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/request/headers.ts), all message functions would need to be async because the internally used `getLocale()` function is async. That is a no-go. Paraglide JS is simple because it does not have any async code by leveraging bundlers to tree-shake messages that are not needed.

AsyncLocalStorage, which works in any other meta framework I have built an adapter for, does not work in NextJS (https://github.com/vercel/next.js/issues/69298). The irony is that the cookie (), header (), etc. APIs even use AsyncLocalStorage under the hood but a custom one that developers can't leverage. Thanks for that.

For anyone starting a new project, I highly recommend choosing a meta framework other than NextJS, such as React Router v7 [(with the new Vite plugin)](https://remix.run/blog/react-router-v7) or [Vike](https://vike.dev/). The tech debt NextJS has accumulated is no joke. Your project will inherit NextJS's tech debt on day 1. What takes a few hours to implement for other meta frameworks takes days for NextJS because most things need custom one-off solutions (sometimes with no solution, such as this issue). Among the reasons (non-exhaustive!): 

- Divergence from web standards 
- Webpack/Turbopack instead of Vite
- Kitchen sink "edge runtime", "perfect for SPAs", "perfect for SSR", "use NextJS for everything" positioning

NextJS can work on the web standards but their tendency for custom solutions and kitchen sink approach will accumulate even more tech debt. As an example, instead of choosing Vite as their new bundler or speeding up and simplifying Webpack, Vercel decided to build their own bundler "Turbopack" from scratch. 

Two years later, Turbopack has not been released, is not going to be faster than Vite, and will not even be fully Webpack compatible. Turbopack does not have a single reason for adoption outside of Vercel/NextJS. 

The result? Turbopack will likely be dead on arrival and a burden for NextJS users. Literally every other meta framework doubled down on Vite. The ecosystem that emerged around Vite is extremely strong—an ecosystem that Turbopack will not be able to catch up to. The Webpack ecosystem is moving to [Rspack](https://rspack.dev/), which is fast and has full backward compatibility with Webpack. The rest is using Vite. Which product other than NextJS is going to use Turbopack?  

I will update the Paraglide NextJS adapter for v2 but won't invest time into removing those warnings anymore. If someone makes a PR and finds a way to use NextJS with AsyncLocalStorage, or makes async `getLocale` to work, please open it.

**Comment by samuelstroschein** [comment]
I invested another two hours (!). The warning has no impact on the usability. But, NextJS has to fix their APIs to resolve this issue. 

By making the `cookie(), header()` etc APIs async in Next JS 15, [despite them being sync under the hood](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/request/headers.ts), all message functions would need to be async because the internally used `getLocale()` function is async. That is a no-go. Paraglide JS is simple because it does not have any async code by leveraging bundlers to tree-shake messages that are not needed.

AsyncLocalStorage, which works in any other meta framework I have built an adapter for, does not work in NextJS (https://github.com/vercel/next.js/issues/69298). The irony is that the cookie (), header (), etc. APIs even use AsyncLocalStorage under the hood but a custom one that developers can't leverage. Thanks for that.

For anyone starting a new project, I highly recommend choosing a meta framework other than NextJS, such as React Router v7 [(with the new Vite plugin)](https://remix.run/blog/react-router-v7) or [Vike](https://vike.dev/). The tech debt NextJS has accumulated is no joke. Your project will inherit NextJS's tech debt on day 1. What takes a few hours to implement for other meta frameworks takes days for NextJS because most things need custom one-off solutions (sometimes with no solution, such as this issue). Among the reasons (non-exhaustive!): 

- Divergence from web standards 
- Webpack/Turbopack instead of Vite
- Kitchen sink "edge runtime", "perfect for SPAs", "perfect for SSR", "use NextJS for everything" positioning

NextJS can work on the web standards but their tendency for custom solutions and kitchen sink approach will accumulate even more tech debt. As an example, instead of choosing Vite as their new bundler or speeding up and simplifying Webpack, Vercel decided to build their own bundler "Turbopack" from scratch. 

Two years later, Turbopack has not been released, is not going to be faster than Vite, and will not even be fully Webpack compatible. Turbopack will not have a single reason for adoption outside of Vercel/NextJS. 

The result? Turbopack will likely be dead on arrival and a burden for NextJS users. Literally every other meta framework doubled down on Vite. The ecosystem that emerged around Vite is extremely strong—an ecosystem that Turbopack will not be able to catch up to. The Webpack ecosystem is moving to [Rspack](https://rspack.dev/), which is fast and has full backward compatibility with Webpack. The rest is using Vite.

**Comment by samuelstroschein** [comment]
I invested another two hours (!). The warning has no impact on the usability. But, NextJS has to fix their APIs to resolve this issue. 

By making the `cookie(), header()` etc APIs async in Next JS 15, [despite them being sync under the hood](https://github.com/vercel/next.js/blob/canary/packages/next/src/server/request/headers.ts), all message functions would need to be async because the internally used `getLocale()` function is async. That is a no-go. Paraglide JS is simple because it does not have any async code by leveraging bundlers to tree-shake messages that are not needed.

AsyncLocalStorage, which works in any other meta framework I have built an adapter for, does not work in NextJS (https://github.com/vercel/next.js/issues/69298). The irony is that the cookie (), header (), etc. APIs even use AsyncLocalStorage under the hood but a custom one that developers can't leverage. Thanks for that.

For anyone starting a new project, I highly recommend choosing a meta framework other than NextJS, such as React Router v7 [(with the new Vite plugin)](https://remix.run/blog/react-router-v7) or [Vike](https://vike.dev/). The tech debt NextJS has accumulated is no joke. Your project will inherit NextJS's tech debt on day 1. What takes a few hours to implement for other meta frameworks takes days for NextJS because most things need custom one-off solutions (sometimes with no solution, such as this issue). Among the reasons (non-exhaustive!): 

- Divergence from web standards 
- Webpack/Turbopack instead of Vite
- Kitchen sink "edge runtime", "perfect for SPAs", "perfect for SSR", "use NextJS for everything" positioning

NextJS can work on the web standards but their tendency for custom solutions and kitchen sink approach will accumulate even more tech debt. As an example, instead of choosing Vite as their new bundler or speeding up and simplifying Webpack, Vercel decided to build their own bundler "Turbopack" from scratch. 

Two years later, Turbopack has not been released, is not going to be faster than Vite, and will not even be fully Webpack compatible. Turbopack will not have a single reason for adoption outside of Vercel/NextJS. 

The result? Turbopack will likely be dead on arrival and a burden for NextJS users. Literally every other meta framework doubled down on Vite. The ecosystem that emerged around Vite is extremely strong—an ecosystem that Turbopack will not be able to catch up to. The Webpack ecosystem is moving to [Rspack](https://rspack.dev/), which is fast and has full backward compatibility with Webpack. The rest is using Vite. So, who is going to adopt Turbopack outside of Vercel/NextJS?

**Comment by samuelstroschein** [comment]
Please upvote https://github.com/vercel/next.js/issues/69298 which will fix this issue and make Paralide's setup with NextJS simpler.

**Comment by samuelstroschein** [comment]
The request has been received by the NextJS team https://github.com/vercel/next.js/discussions/76582#discussioncomment-12382562.
