### ISSUE TITLE
Issue with deno

### ISSUE THREAD

**Issue by aguilera51284** [opral/inlang-paraglide-js#86]
i have this command with Deno:

`paraglide": "deno run --unstable --allow-read=. --allow-write=.  npm:@inlang/paraglide-js compile --project ./project.inlang --outdir ./src/paraglide`

and i have this error:

![image](https://github.com/opral/inlang-paraglide-js/assets/7749319/9d9c1a05-3aa5-4f16-9f70-7cf6dd7ffe25)

Deno: 1.42.4

**Comment by LorisSigrist** [comment]
This seems to be an issue with the way the Inlang SDK reads files. We'll take a look!

**Comment by jldec** [comment]
This appears to be a deno-specific node:\* polyfill issue.<br>See [https://github.com/denoland/deno/issues/23562](https://github.com/denoland/deno/issues/23562)

**Comment by jldec** [comment]
Closing this pending deno compatibility fix<br>Please re-open (or suggest a workaround) if support for deno becomes essential.

**Comment by HighPriest** [comment]
I would like to add to this topic.  
Moving dependency management from `package.json` to `deno.json`, resulted in this error during build
```fish
error: Uncaught (in worker "") (in promise) TypeError: Could not find package '$app' from referrer 'file:///E:/project/node_modules/.deno/@inlang+paraglide-sveltekit@0.11.5/node_modules/@inlang/paraglide-sveltekit/dist/runtime/adapter.server.js'.
    ...await import("./hooks.server.js"),
       ^
    at async get_hooks (file:///E:/project/.svelte-kit/output/server/chunks/internal.js:605:8)
    at async Server.init (file:///E:/project/.svelte-kit/output/server/index.js:3790:24)
    at async prerender (file:///E:/project/node_modules/.deno/@sveltejs+kit@2.7.2/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:453:2)    
    at async file:///E:/project/node_modules/.deno/@sveltejs+kit@2.7.2/node_modules/@sveltejs/kit/src/utils/fork.js:23:16
error: Uncaught (in promise) Error: Unhandled error. ([Object: null prototype] {
  message: "Uncaught (in promise) TypeError: Could not find package '$app' from referrer 'file:///E:/project/node_modules/.deno/@inlang+paraglide-sveltekit@0.11.5/node_modules/@inlang/paraglide-sveltekit/dist/runtime/adapter.server.js'.",
  fileName: 'file:///E:/project/.svelte-kit/output/server/chunks/internal.js',
  lineNumber: 605,
  columnNumber: 8
})
    at NodeWorker.emit (ext:deno_node/_events.mjs:381:17)
    at NodeWorker.#handleError (node:worker_threads:117:10)
    at NodeWorker.#pollControl (node:worker_threads:137:30)
    at eventLoopTick (ext:core/01_core.js:175:7)
 ```

All my dependencies:
```
npm:@inlang/paraglide-sveltekit@^0.11.5
npm:@sveltejs/adapter-auto@3.3.0
npm:@sveltejs/kit@2.7.2
npm:@sveltejs/vite-plugin-svelte@4.0.0
npm:@ts-ghost/content-api@4.1.0
npm:@types/eslint@9.6.1
npm:eslint@9.13.0
npm:eslint-config-prettier@9.1.0
npm:eslint-plugin-svelte@2.46.0
npm:globals@15.11.0
npm:prettier@3.3.3
npm:prettier-plugin-svelte@3.2.7
npm:sass-embedded@1.80.4
npm:svelte@5.1.1
npm:svelte-check@4.0.5
npm:svelte-sitemap@^2.6.0
npm:sveltekit-adapter-deno@0.16.0
npm:typescript@5.6.3
npm:typescript-eslint@8.11.0
npm:vite@5.4.10
```

**Comment by HighPriest** [comment]
Nevermind.  
It was an error in `deno.json` imports notation:
- `npm:@inlang/paraglide-sveltekit@^0.11.5` -> `npm:@inlang/paraglide-sveltekit@0.11.5`

Was all that was needed to fix the issue

**Comment by HighPriest** [comment]
`"@inlang/paraglide-sveltekit": "^0.11.5"` has to be present in package.json. Otherwise the build process fails.
